# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
#   build:
#     environment: twitter
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x, 16.x, 18.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v3
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - name: Print name
#       env: 
#         TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
#       run: echo "username is $TWITTER_USERNAME" 
#     - name: Set env
#       run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
#     - name: Test
#       run: echo $GITHUB_SHA_SHORT
#     - run: npm ci
#     - run: npm start
  run:
    environment: twitter
    name: Running the twitter bot...
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [18.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - name: Print name
      env: 
        OPENAI_API_KEY: ${{ secrets.u4s81lcxhvTrm3y8WZb6T3BlbkFJvLhnMWfQj7rO815Tioou }}
        TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        TEST: Mona
      run: |
        echo ${{secrets.TWITTER_USERNAME }} | sed 's/./& /g'
    - name: npm install, build and test
      env: 
        OPENAI_API_KEY: ${{ secrets.u4s81lcxhvTrm3y8WZb6T3BlbkFJvLhnMWfQj7rO815Tioou }}
        TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }}
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
        TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        npm install
        npm run build --if-present
        npm start
