# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  run:
    environment: twitter
    name: Running the twitter bot...
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [18.x]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node_version }}
    - name: create env file
      run: |
        touch .env
        echo OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} >> .env
        echo TWITTER_USERNAME: ${{ secrets.TWITTER_USERNAME }} >> .env
        echo TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }} >> .env
        echo TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }} >> .env
        echo TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }} >> .env
        echo TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }} >> .env
        echo TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} >> .env
    - name: npm install, build and test
      run: |
        npm install
        npm run github-build
        npm start
